/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, RootState } from "@react-three/fiber";

export default function ValueBtn(props: any) {
    const { nodes, materials }: any = useGLTF("/models/buttons/value-button.glb");

    const groupRef = useRef<THREE.Group>(null);

    useFrame((state: RootState) => {
        const time = state.clock.getElapsedTime();
        if (groupRef.current) {
            groupRef.current.position.y = Math.sin(time * 2) * 0.05;
        }
    });

    return (
        <group {...props} position={[0, -3.8, 0]} dispose={null}>
            <group ref={groupRef}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.btn_values.geometry}
                    material={materials.Darkest}
                    position={[-4.398, 2.837, -6.204]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 6]}
                    scale={0.6}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane024.geometry}
                    material={materials["Sun light"]}
                    position={[-4.433, 2.803, -6.221]}
                    rotation={[1.588, 0.03, -0.524]}
                    scale={[1.2, 1, 0.46]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/buttons/value-button.glb");