/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Gltf} from "@react-three/drei";
import { useFrame, RootState } from "@react-three/fiber";

export default function CurrentBtn(props: any) {
    const { nodes, materials }: any = useGLTF("/models/buttons/current-button.glb");

    const groupRef = useRef<THREE.Group>(null);

    useFrame((state: RootState) => {
        const time = state.clock.getElapsedTime();
        if (groupRef.current) {
            groupRef.current.position.y = Math.sin(time * 2) * 0.05;
        }
    });

    return (
        <group {...props} position={[0, -3.8, 0]} dispose={null}>
            <group ref={groupRef}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.btn_Current_Project.geometry}
                    material={materials.Darker}
                    position={[5.951, 4.474, -3.228]}
                    rotation={[Math.PI / 2, 0, 1.049]}
                    scale={0.6}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane025.geometry}
                    material={materials["Color 2"]}
                    position={[6.405, 4.427, -2.514]}
                    rotation={[-0.18, 0.517, -1.481]}
                    scale={[0.5, 1, 1.4]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/buttons/current-button.glb");