/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef} from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, RootState } from "@react-three/fiber";

export default function IntroductionBtn(props: any) {
    const { nodes, materials }: any = useGLTF("/models/buttons/introduction-button.glb");

    const groupRef = useRef<THREE.Group>(null);

    useFrame((state: RootState) => {
        const time = state.clock.getElapsedTime();
        if (groupRef.current) {
            groupRef.current.position.y = Math.sin(time * 2) * 0.05;
        }
    });

    return (
        <group {...props} position={[0, -3.8, 0]} dispose={null}>
            <group ref={groupRef}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Text004.geometry}
                    material={materials.Lighter}
                    position={[1.33, 3.041, 6.391]}
                    rotation={[Math.PI / 2, 0, Math.PI]}
                    scale={0.6}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane023.geometry}
                    material={materials.Brown}
                    position={[0.011, 3.2, 6.448]}
                    rotation={[Math.PI / 2, 0.037, 0]}
                    scale={[1.65, 1, 0.35]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/buttons/introduction-button.glb");